# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - npm install cordova
  - npm install
  - npm link

image: Visual Studio 2017

build: off

test_script:
  - node --version
  - npm --version
  - npm run test-appveyor
